def pizzas():
    return [
        {'id': 1, 'name': 'Margherita'},
        {'id': 2, 'name': 'Pepperoni'},
        {'id': 3, 'name': 'Reine'},
        {'id': 4, 'name': 'Hawaïenne'},
        {'id': 5, 'name': '4 Fromages'},
        {'id': 6, 'name': 'Mexicaine'},
        {'id': 7, 'name': 'Saumon fumé'},
        {'id': 8, 'name': '4 saisons'},
        {'id': 9, 'name': 'Pizza Carrée'},
        {'id': 10, 'name': 'Chèvre-miel'},]

def ingredients():
    return [
        {'id': 1, 'name': 'Sauce tomates', 'available': True},
        {'id': 2, 'name': 'Mozzarella', 'available': True},
        {'id': 3, 'name': 'Pepperoni', 'available': True},
        {'id': 4, 'name': 'Jambon', 'available': True},
        {'id': 5, 'name': 'Champignon', 'available': True},
        {'id': 6, 'name': 'Gorgonzola', 'available': True},
        {'id': 7, 'name': 'Chèvre', 'available': True},
        {'id': 8, 'name': 'Miel', 'available': True},
        {'id': 9, 'name': 'Parmesan', 'available': True},
        {'id': 10, 'name': 'Ananas', 'available': True},
        {'id': 12, 'name': 'Poivron', 'available': True},
        {'id': 13, 'name': 'Basilic', 'available': True},
        {'id': 14, 'name': 'Boeuf haché', 'available': True},
        {'id': 15, 'name': 'Jalapenos', 'available': True},
        {'id': 16, 'name': 'Crème fraiche', 'available': True},
        {'id': 17, 'name': 'Saumon fumé', 'available': True},
        {'id': 18, 'name': 'Olives noirs', 'available': True},
        {'id': 19, 'name': 'Maïs', 'available': True},
        {'id': 20, 'name': 'Oignon', 'available': True}]

def recettes():
    return [
        {'id_pizza' : 1, 'id_ingredient': 1}, 
        {'id_pizza' : 1, 'id_ingredient': 2}, 
        {'id_pizza' : 1, 'id_ingredient': 13},
        {'id_pizza' : 2, 'id_ingredient': 1}, 
        {'id_pizza' : 2, 'id_ingredient': 2}, 
        {'id_pizza' : 2, 'id_ingredient': 3},
        {'id_pizza' : 3, 'id_ingredient': 1}, 
        {'id_pizza' : 3, 'id_ingredient': 2}, 
        {'id_pizza' : 3, 'id_ingredient': 4},
        {'id_pizza' : 3, 'id_ingredient': 5}, 
        {'id_pizza' : 4, 'id_ingredient': 1}, 
        {'id_pizza' : 4, 'id_ingredient': 2},
        {'id_pizza' : 4, 'id_ingredient': 4},
        {'id_pizza' : 4, 'id_ingredient': 10}, 
        {'id_pizza' : 5, 'id_ingredient': 1},
        {'id_pizza' : 5, 'id_ingredient': 2}, 
        {'id_pizza' : 5, 'id_ingredient': 6}, 
        {'id_pizza' : 5, 'id_ingredient': 9},
        {'id_pizza' : 5, 'id_ingredient': 7}, 
        {'id_pizza' : 6, 'id_ingredient': 1}, 
        {'id_pizza' : 6, 'id_ingredient': 2},
        {'id_pizza' : 6, 'id_ingredient': 14},
        {'id_pizza' : 6, 'id_ingredient': 15}, 
        {'id_pizza' : 6, 'id_ingredient': 19},
        {'id_pizza' : 7, 'id_ingredient': 2},
        {'id_pizza' : 7, 'id_ingredient': 16}, 
        {'id_pizza' : 7, 'id_ingredient': 17}, 
        {'id_pizza' : 8, 'id_ingredient': 1}, 
        {'id_pizza' : 8, 'id_ingredient': 2},
        {'id_pizza' : 8, 'id_ingredient': 4},
        {'id_pizza' : 8, 'id_ingredient': 5}, 
        {'id_pizza' : 8, 'id_ingredient': 18},
        {'id_pizza' : 9, 'id_ingredient': 1},
        {'id_pizza' : 9, 'id_ingredient': 20}, 
        {'id_pizza' : 9, 'id_ingredient': 18},
        {'id_pizza' : 10, 'id_ingredient': 1},
        {'id_pizza' : 10, 'id_ingredient': 2},
        {'id_pizza' : 10, 'id_ingredient': 7},
        {'id_pizza' : 10, 'id_ingredient': 8}]