def pizzas():
    return [
        {'id': 1, 'name': 'Margherita'},
        {'id': 2, 'name': 'Pepperoni'},
        {'id': 3, 'name': 'Reine'},
        {'id': 4, 'name': 'Hawaïenne'},
        {'id': 5, 'name': '4 Fromages'},
        {'id': 6, 'name': 'Mexicaine'},
        {'id': 7, 'name': 'Saumon fumé'},
        {'id': 8, 'name': '4 saisons'},
        {'id': 9, 'name': 'Pizza Carrée'},
        {'id': 10, 'name': 'Chèvre-miel'},]

def ingredients():
    return [
        {'id': 1, 'name': 'Sauce tomates'},
        {'id': 2, 'name': 'Mozzarella'},
        {'id': 3, 'name': 'Pepperoni'},
        {'id': 4, 'name': 'Jambon'},
        {'id': 5, 'name': 'Champignon'},
        {'id': 6, 'name': 'Gorgonzola'},
        {'id': 7, 'name': 'Chèvre'},
        {'id': 8, 'name': 'Miel'},
        {'id': 9, 'name': 'Parmesan'},
        {'id': 10, 'name': 'Ananas'},
        {'id': 12, 'name': 'Poivron'},
        {'id': 13, 'name': 'Basilic'},
        {'id': 14, 'name': 'Boeuf haché'},
        {'id': 15, 'name': 'Jalapenos'},
        {'id': 16, 'name': 'Crème fraiche'},
        {'id': 17, 'name': 'Saumon fumé'},
        {'id': 18, 'name': 'Olives noirs'},
        {'id': 19, 'name': 'Maïs'},
        {'id': 20, 'name': 'Oignon'}]

def recettes():
    return [
        {'id_pizza' : 1, 'id_ingredient': 1}, 
        {'id_pizza' : 1, 'id_ingredient': 2}, 
        {'id_pizza' : 1, 'id_ingredient': 13},
        {'id_pizza' : 2, 'id_ingredient': 1}, 
        {'id_pizza' : 2, 'id_ingredient': 2}, 
        {'id_pizza' : 2, 'id_ingredient': 3},
        {'id_pizza' : 3, 'id_ingredient': 1}, 
        {'id_pizza' : 3, 'id_ingredient': 2}, 
        {'id_pizza' : 3, 'id_ingredient': 4},
        {'id_pizza' : 3, 'id_ingredient': 5}, 
        {'id_pizza' : 4, 'id_ingredient': 1}, 
        {'id_pizza' : 4, 'id_ingredient': 2},
        {'id_pizza' : 4, 'id_ingredient': 4},
        {'id_pizza' : 4, 'id_ingredient': 10}, 
        {'id_pizza' : 5, 'id_ingredient': 1},
        {'id_pizza' : 5, 'id_ingredient': 2}, 
        {'id_pizza' : 5, 'id_ingredient': 6}, 
        {'id_pizza' : 5, 'id_ingredient': 9},
        {'id_pizza' : 5, 'id_ingredient': 7}, 
        {'id_pizza' : 6, 'id_ingredient': 1}, 
        {'id_pizza' : 6, 'id_ingredient': 2},
        {'id_pizza' : 6, 'id_ingredient': 14},
        {'id_pizza' : 6, 'id_ingredient': 15}, 
        {'id_pizza' : 6, 'id_ingredient': 19},
        {'id_pizza' : 7, 'id_ingredient': 2},
        {'id_pizza' : 7, 'id_ingredient': 16}, 
        {'id_pizza' : 7, 'id_ingredient': 17}, 
        {'id_pizza' : 8, 'id_ingredient': 1}, 
        {'id_pizza' : 8, 'id_ingredient': 2},
        {'id_pizza' : 8, 'id_ingredient': 4},
        {'id_pizza' : 8, 'id_ingredient': 5}, 
        {'id_pizza' : 8, 'id_ingredient': 18},
        {'id_pizza' : 9, 'id_ingredient': 1},
        {'id_pizza' : 9, 'id_ingredient': 20}, 
        {'id_pizza' : 9, 'id_ingredient': 18},
        {'id_pizza' : 10, 'id_ingredient': 1},
        {'id_pizza' : 10, 'id_ingredient': 2},
        {'id_pizza' : 10, 'id_ingredient': 7},
        {'id_pizza' : 10, 'id_ingredient': 8}]